### ISSUE TITLE
Advice on filtering documents collection based on folders

### ISSUE THREAD

**Issue by johannesburg** [jpoehnelt/eleventy-google-docs-starter#4]
Hello!

I'm excited to use this as the basis for a small static site I'm working on, but I'm wondering if I could ask a few questions about its implementation? Specifically, I'd ideally like to be able to filter what documents get displayed on the index page e.g. based on what google drive folder they're in, or even include additional metadata per file (date written, a 'display' attribute, etc). 

I'm curious if you have thoughts about how you'd go about filtering, as the process by which google docs get added to the 'documents' collection is still a bit obscure to me.

Thank you in advance,
Johan

**Comment by jpoehnelt** [comment]
For filtering of the index page, see [11ty.dev/docs/collections/](https://www.11ty.dev/docs/collections/). It is just iterating over collections of document types defined through pagination in src/doc.njk.

For filtering which docs are downloaded from drive, see: https://github.com/jpoehnelt/eleventy-google-docs-starter/blob/main/src/_data/docs.js#L92-L94 which creates the global data available to templates.

For modifying what is displayed, see the [11ty.dev/docs/filters/log/](https://www.11ty.dev/docs/filters/log/) and https://developers.google.com/docs/api/reference/rest/v1/documents#Document for more information on fields available for the Document.
